import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./footer/footer";
import { GlassmorphismNav } from "./components/glassmorphism-nav";
import Script from "next/script";
import { Yrsa } from "next/font/google";
import Seo from "./components/Seo";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/next"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const yrsa = Yrsa({
  subsets: ["latin"],
  variable: "--font-yrsa",
  weight: ["300", "400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Traning And Placement Cell Shyam Lal College",
  description: "Generated by Hardik Jain",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${yrsa.variable}  antialiased bg-[#F7F1E8] text-[#37322F]`}
      >
        <div className="min-h-screen flex flex-col bg-gradient-to-b from-white to-gray-100 dark:from-slate-400 dark:to-white text-gray-900">
          <div className="pointer-events-none fixed inset-0 z-0">
          <div
            className="absolute inset-0 opacity-[0.10] "
            style={{
              backgroundImage: "url(/slccutout.avif)",
              backgroundRepeat: "cover",
              backgroundPosition: "top left",
              backgroundSize: "cover",
              filter: "contrast(1.05) brightness(1.05)",
            }}
          />
          {/* Soft vignette to blend with theme */}
          {/* <div className="absolute inset-0 bg-gradient-to-b from-[#F7F1E8] via-transparent to-[#F7F1E8]" /> */}
        </div>
          <GlassmorphismNav />
          <Seo />
          <main className="flex-1 w-full">{children}</main>
          <Footer />
          <SpeedInsights/>
          <Analytics/>
        </div>

        <Script
          type="module"
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
          strategy="afterInteractive"
          crossOrigin="anonymous"
        />
        <Script
          noModule
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
          strategy="afterInteractive"
          crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}
